name: Testes Unitários

on:
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Instalar Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Instalar dependências (se houver)
      run: |
        python -m pip install --upgrade pip

    - name: Rodar testes
      run: |
        python -m unittest discover
