name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # O workflow roda quando algo é enviado para a branch main

jobs:
  build:
    runs-on: ubuntu-latest  # Usa o Ubuntu para o ambiente de build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Baixa o repositório
      - name: Rodar testes
        run: echo "Rodando os testes..."

  deploy:
    needs: build  # O deploy depende do build
    runs-on: ubuntu-latest  # Também roda no Ubuntu
    steps:
      - name: Simulação de Deploy
        run: echo "Simulando o deploy..."
