name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run tests
        run: echo "Testes rodando..."

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Simulação de Deploy
        run: echo "Simulando o deploy..."

