name: CI/CD - Petshop Project

on:
  push:
    branches: [ main, atividade-formativa-semana-2 ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build e Testes
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configura Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instala dependências
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Roda os testes com pytest
      run: |
        pytest

  deploy:
    name: Simulação de Deploy
    runs-on: ubuntu-latest
    needs: build  # só roda se o build passar

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Simula deploy copiando arquivos para dist/
      run: |
        mkdir -p dist
        cp *.py dist/
        echo "Deploy simbólico concluído com sucesso!"
