name: CI - Testes e Qualidade de Código

on:
  push:
    branches: [ main, atividade-formativa-semana-2 ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configura Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instala dependências
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Roda os testes com pytest
      run: |
        pytest

